// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fDOnIYkgQzZnNKk1GFsXobMJnWbnWJg',
    appId: '1:225626396798:web:b002626264a6e0fbb0a02f',
    messagingSenderId: '225626396798',
    projectId: 'stonelotus-3b34a',
    authDomain: 'stonelotus-3b34a.firebaseapp.com',
    databaseURL: 'https://stonelotus-3b34a-default-rtdb.firebaseio.com',
    storageBucket: 'stonelotus-3b34a.firebasestorage.app',
    measurementId: 'G-5K93D6N3ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv0ynpcXeJPkkQpMV2RTXwsshCteHQWK0',
    appId: '1:225626396798:android:0f552c3dae6efae7b0a02f',
    messagingSenderId: '225626396798',
    projectId: 'stonelotus-3b34a',
    databaseURL: 'https://stonelotus-3b34a-default-rtdb.firebaseio.com',
    storageBucket: 'stonelotus-3b34a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJBbGka6B6kyRS1_-jO3NwBSc3kP0FTqE',
    appId: '1:225626396798:ios:e5bf7acd81229a38b0a02f',
    messagingSenderId: '225626396798',
    projectId: 'stonelotus-3b34a',
    databaseURL: 'https://stonelotus-3b34a-default-rtdb.firebaseio.com',
    storageBucket: 'stonelotus-3b34a.firebasestorage.app',
    iosBundleId: 'com.example.stoneLotus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJBbGka6B6kyRS1_-jO3NwBSc3kP0FTqE',
    appId: '1:225626396798:ios:e5bf7acd81229a38b0a02f',
    messagingSenderId: '225626396798',
    projectId: 'stonelotus-3b34a',
    databaseURL: 'https://stonelotus-3b34a-default-rtdb.firebaseio.com',
    storageBucket: 'stonelotus-3b34a.firebasestorage.app',
    iosBundleId: 'com.example.stoneLotus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3fDOnIYkgQzZnNKk1GFsXobMJnWbnWJg',
    appId: '1:225626396798:web:25b2ae9aabcae6d7b0a02f',
    messagingSenderId: '225626396798',
    projectId: 'stonelotus-3b34a',
    authDomain: 'stonelotus-3b34a.firebaseapp.com',
    databaseURL: 'https://stonelotus-3b34a-default-rtdb.firebaseio.com',
    storageBucket: 'stonelotus-3b34a.firebasestorage.app',
    measurementId: 'G-32H6HFFWE9',
  );
}
